In [1]:
import numpy as np
inventory = np.array([
    [100, 150, 200, 250],  # Product 1
    [120, 180, 240, 300],  # Product 2
    [130, 190, 260, 310],  # Product 3
    [140, 210, 280, 350],  # Product 4
    [150, 220, 290, 360]   # Product 5
])
num_dimensions = inventory.ndim
print(f"Number of dimensions: {num_dimensions}")

Number of dimensions: 2


In [2]:
data_type = inventory.dtype
print(f"Data type: {data_type}")

Data type: int64


In [3]:
memory_usage = inventory.nbytes
print(f"Memory usage: {memory_usage} bytes")

Memory usage: 160 bytes


In [4]:
inventory += 20
print("Inventory after adding 20 units to all products:")
print(inventory)

Inventory after adding 20 units to all products:
[[120 170 220 270]
 [140 200 260 320]
 [150 210 280 330]
 [160 230 300 370]
 [170 240 310 380]]


In [5]:
inventory[2] -= 10  # Product 3 is at index 2
print("Inventory after deducting 10 units from Product 3:")
print(inventory)

Inventory after deducting 10 units from Product 3:
[[120 170 220 270]
 [140 200 260 320]
 [140 200 270 320]
 [160 230 300 370]
 [170 240 310 380]]


In [6]:
inventory[:, 1] *= 2  # Location 2 is at index 1
print("Inventory after doubling the stock at Location 2:")
print(inventory)

Inventory after doubling the stock at Location 2:
[[120 340 220 270]
 [140 400 260 320]
 [140 400 270 320]
 [160 460 300 370]
 [170 480 310 380]]


In [7]:
max_capacity = 1000
percentage_stock = (inventory / max_capacity) * 100
print("Percentage of stock available for each product at all locations:")
print(percentage_stock)

Percentage of stock available for each product at all locations:
[[12. 34. 22. 27.]
 [14. 40. 26. 32.]
 [14. 40. 27. 32.]
 [16. 46. 30. 37.]
 [17. 48. 31. 38.]]


In [8]:
total_stock_per_product = inventory.sum(axis=1)
print("Total stock of each product across all locations:")
print(total_stock_per_product)

Total stock of each product across all locations:
[ 950 1120 1130 1290 1340]


In [9]:
total_stock_per_location = inventory.sum(axis=0)
print("Total stock available in each location:")
print(total_stock_per_location)

Total stock available in each location:
[ 730 2080 1360 1660]


In [10]:
product_with_max_stock = np.argmax(total_stock_per_product)
print(f"Product with maximum total stock: Product {product_with_max_stock + 1}")

Product with maximum total stock: Product 5


In [11]:
location_with_min_stock = np.argmin(total_stock_per_location)
print(f"Location with minimum total stock: Location {location_with_min_stock + 1}")

Location with minimum total stock: Location 1


In [12]:
average_stock_per_product = inventory.mean(axis=1)
print("Average stock per product across all locations:")
print(average_stock_per_product)

Average stock per product across all locations:
[237.5 280.  282.5 322.5 335. ]


In [13]:
total_elements = inventory.size
print(f"Total number of elements in the array: {total_elements}")

Total number of elements in the array: 20


In [14]:
product_2_stock = inventory[1, :]
print("Stock levels of Product 2 across all locations:")
print(product_2_stock)

Stock levels of Product 2 across all locations:
[140 400 260 320]


In [15]:
location_3_stock = inventory[:, 2]
print("Stock levels for all products in Location 3:")
print(location_3_stock)

Stock levels for all products in Location 3:
[220 260 270 300 310]


In [16]:
selected_stock = inventory[2:4, [1, 3]]
print("Stock levels of Products 3 and 4 for Locations 2 and 4:")
print(selected_stock)

Stock levels of Products 3 and 4 for Locations 2 and 4:
[[400 320]
 [460 370]]


In [17]:
sliced_stock = inventory[:3, :2]
print("Stock levels of the first 3 products for the first 2 locations:")
print(sliced_stock)

Stock levels of the first 3 products for the first 2 locations:
[[120 340]
 [140 400]
 [140 400]]


In [18]:
sliced_stock = inventory[3:, 2:]
print("Stock levels of the last 2 products for the last 2 locations:")
print(sliced_stock)

Stock levels of the last 2 products for the last 2 locations:
[[300 370]
 [310 380]]


In [20]:
product_5_location_3_stock = inventory[4, 2]
print("Stock level of Product 5 at Location 3:", product_5_location_3_stock)

Stock level of Product 5 at Location 3: 310


In [21]:
selected_stock = inventory[[0, 3], [0, 2]]
print("Stock levels of Product 1 at Location 1 and Product 4 at Location 3:")
print(selected_stock)

Stock levels of Product 1 at Location 1 and Product 4 at Location 3:
[120 300]


In [23]:
inventory[1, 3] = 100
print("Inventory after updating the stock of Product 2 at Location 4:")
print(inventory)

Inventory after updating the stock of Product 2 at Location 4:
[[120 340 220 270]
 [140 400 260 100]
 [140 400 270 320]
 [160 460 300 370]
 [170 480 310 380]]
