In [2]:
import numpy as np
a = np.array([
    [100,200,150,300],
    [50,60,40,80],
    [300,400,350,500],
    [200,250,220,270],
    [80,90,70,100]
])

In [5]:
dimensions = a.ndim
print("Number of dimensions:", dimensions)

Number of dimensions: 2


In [6]:
data_type = a.dtype
print("Data type:", data_type)

Data type: int64


In [7]:
total_elements = a.size
print("Total elements:", total_elements)

Total elements: 20


In [8]:
memory_usage = a.nbytes
print("Memory usage (bytes):", memory_usage)

Memory usage (bytes): 160


In [9]:
updated_stock = a + 20
print("Updated stock after adding 20:", updated_stock)

Updated stock after adding 20: [[120 220 170 320]
 [ 70  80  60 100]
 [320 420 370 520]
 [220 270 240 290]
 [100 110  90 120]]


In [10]:
a[2] -= 10
print("Stock after deducting 10 from Product 3:", a[2])

Stock after deducting 10 from Product 3: [290 390 340 490]


In [11]:
a[:, 1] *= 2
print("Stock after doubling Location 2:", a)

Stock after doubling Location 2: [[100 400 150 300]
 [ 50 120  40  80]
 [290 780 340 490]
 [200 500 220 270]
 [ 80 180  70 100]]


In [12]:
max_capacity = 1000
percentage_stock = (a / max_capacity) * 100
print("Stock percentage:", percentage_stock)

Stock percentage: [[10. 40. 15. 30.]
 [ 5. 12.  4.  8.]
 [29. 78. 34. 49.]
 [20. 50. 22. 27.]
 [ 8. 18.  7. 10.]]


In [13]:
product_totals = np.sum(a, axis=1)
print("Total stock per product:", product_totals)

Total stock per product: [ 950  290 1900 1190  430]


In [14]:
location_totals = np.sum(a, axis=0)
print("Total stock per location:", location_totals)

Total stock per location: [ 720 1980  820 1240]


In [15]:
max_stock_per_location = np.max(a, axis=0)
print("Max stock per location:", max_stock_per_location)

Max stock per location: [290 780 340 490]


In [16]:
min_stock_per_product = np.min(a, axis=1)
print("Min stock per product:", min_stock_per_product)

Min stock per product: [100  40 290 200  70]


In [17]:
avg_stock_per_product = np.mean(a, axis=1)
print("Average stock per product:", avg_stock_per_product)

Average stock per product: [237.5  72.5 475.  297.5 107.5]


In [18]:
a_product_2 = a[1]
print("Stock levels of Product 2:", a_product_2)

Stock levels of Product 2: [ 50 120  40  80]


In [19]:
a_location_3 = a[:, 2]
print("Stock levels at Location 3:", a_location_3)

Stock levels at Location 3: [150  40 340 220  70]


In [20]:
bb = a[[2, 3], [1, 3]]
print("Stock of Product 3 at Location 2 and Product 4 at Location 4:", bb)

Stock of Product 3 at Location 2 and Product 4 at Location 4: [780 270]


In [21]:
subset_1 = a[0:3, 0:2]
print("Stock of first 3 products at first 2 locations:", subset_1)

Stock of first 3 products at first 2 locations: [[100 400]
 [ 50 120]
 [290 780]]


In [22]:
subset_2 = a[3:5, 2:4]
print("Stock of last 2 products at last 2 locations:", subset_2)

Stock of last 2 products at last 2 locations: [[220 270]
 [ 70 100]]


In [23]:
stock_p5_l3 = a[4, 2]
print("Stock of Product 5 at Location 3:", stock_p5_l3)

Stock of Product 5 at Location 3: 70


In [24]:
products = [0, 3]
locations = [0, 2]
stock_levels = a[products, locations]
print("Stock levels of Product 1 at Location 1 and Product 4 at Location 3:", stock_levels)

Stock levels of Product 1 at Location 1 and Product 4 at Location 3: [100 220]


In [25]:
a[1, 3] = 100
print("Updated stock array:", a)

Updated stock array: [[100 400 150 300]
 [ 50 120  40 100]
 [290 780 340 490]
 [200 500 220 270]
 [ 80 180  70 100]]
