In [1]:
import numpy as np
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.size

20

In [2]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.dtype

dtype('int64')

In [3]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.itemsize

8

In [4]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a.sum()

np.int64(3810)

In [5]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[2]-=10
print(a)

[[100 200 150 300]
 [ 50  60  40  80]
 [290 390 340 490]
 [200 250 220 270]
 [ 80  90  70 100]]


In [6]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a+=20
print(a)

[[120 220 170 320]
 [ 70  80  60 100]
 [320 420 370 520]
 [220 270 240 290]
 [100 110  90 120]]


In [7]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[0:6,1]*=2
print(a)

[[100 400 150 300]
 [ 50 120  40  80]
 [300 800 350 500]
 [200 500 220 270]
 [ 80 180  70 100]]


In [8]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.sum(a,axis=0)

array([ 730, 1000,  830, 1250])

In [9]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.sum(a,axis=1)

array([ 750,  230, 1550,  940,  340])

In [10]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.min(a,axis=1)

array([100,  40, 300, 200,  70])

In [11]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.max(a,axis=0)

array([300, 400, 350, 500])

In [12]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
np.mean(a,axis=1)

array([187.5,  57.5, 387.5, 235. ,  85. ])

In [13]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[1]

array([50, 60, 40, 80])

In [14]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[:,3]

array([300,  80, 500, 270, 100])

In [15]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[0:3,0:2]

array([[100, 200],
       [ 50,  60],
       [300, 400]])

In [16]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[3:6,2:4]

array([[220, 270],
       [ 70, 100]])

In [18]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[4:6,3:4]

array([[100]])

In [19]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[1,3]=100
print(a)

[[100 200 150 300]
 [ 50  60  40 100]
 [300 400 350 500]
 [200 250 220 270]
 [ 80  90  70 100]]


In [20]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
a[0:0]
a[3,2]

np.int64(220)

In [21]:
a= np.array([
    [100,200,150,300], #product1
    [50,60,40,80],     #product2
    [300,400,350,500], #product3
    [200,250,220,270], #product4
    [80,90,70,100]     #product5
])
stock_level=a[[0,3],[0,2]]
stock_level

array([100, 220])